name: Publish Release

on:
  - workflow_dispatch
  - push
      branches:
        - master
  - schedule:
      - cron: '0 0 * * *' # Once per day at midnight

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authorize
        run: gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: cd .scripts && sh ./package.sh
