name: Publish Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Authorize
          run: gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}

        - name: Release
          run: cd .scripts && sh ./package.sh
